* 빌드 시 주의 사항
1. platform의 lib 요소가 제대로 설치되지 않는 경우는 전체 빌드가 실패할 수 있음
   예) libcurl 헤더 일부 누락시 http 및 httpn 드라이버 빌드 실패

2. 이런 경우, 각 빌드 경로 아래에서 필요한 부분만 make & make install 실행하길바람2. 이런 경우, 각 빌드 경로 아래에서 필요한 부분만 make & make install 실행하길바람
